name: twitter-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - fastapi
    - requests
    - uvicorn[standard]
    - selenium
    - python-chromedriver-binary  # Replace <version> with the desired version of chromedriver-binary
