service: twitter-api

provider:
  name: aws
  runtime: python3.8

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  send_reset_email:
    handler: handler.send_reset_email
    events:
      - http:
          path: send-reset-email
          method: get
